### ISSUE TITLE
didn't work when crawling from google search engine

### ISSUE THREAD

**Issue by stutys** [wolfhong/python-pisces#1]
hi wlfhong, thanks for  your great work. I haved this code to crawl images from baidu image. But when chage the search engine from baidu to google, it returns nothing.
Can you give some suggestions? thanks so much!

**Comment by wolfhong** [comment]
Hi @stutys , I'm so sorry that I haven't maintained my github for a long time, thank you using it.
Pisces had released to pypi, you can use `pip install python-pisces` and then use `pisces -h` to use it.
It had been tested on Windows, Mac and Linux. I hope it can help you.
